
version: '3.1'

services:
  frontend:
    build:
      dockerfile: dockerfile
      context: .

    image: filetag
    container_name: file_container
    restart: always
    ports:
      - 8080:3000



    