name: learn-github-actions

on:
  push:
    branches:
      - "master"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker
        run: |
          sudo service docker start

      - name: taked down previous cmd
        run: |
          docker compose down

      - name: taked up cmd
        run: |
          docker compose up -d 
      - name: Build
        run: |
          npm run build    



